language: node_js
node_js:
  - "10"

jobs:
  include:
    - env:
        - job=lint
      script: npm run lint
    - env:
        - job=test
      script: npm run test
    - env:
        - job=build
      script:
        - npm install
        - npm run build
    - env:
        - job=docker-build
      script: docker build --no-cache .
