language: node_js
node_js:
  - "16"

jobs:
  include:
    - env:
        - job=lint
      script: npm run lint
    - env:
        - job=test
      script: npm run test
    - env:
        - job=build
      script:
        - export NODE_OPTIONS=--max_old_space_size=8192;
        - npm install
        - npm rebuild node-sass
        - npm run build
        - npm run build-lib
    - env:
        - job=docker-build
      script:
        - export NODE_OPTIONS=--max_old_space_size=8192;
        - docker build --no-cache .
    # - env:
    #     - job=check_i18n
    #   script: ./checki18n.sh
