language: node_js
node_js:
  - "8"

before_script:
    - ./scripts/prebuild.sh

jobs:
  include:
    - env:
        - job=lint
      script: npm run lint
    - env:
        - job=test
      script: npm run test
    - env:
        - job=build
      script: npm run build
    - env:
        - job=docker-build
      script: docker build --no-cache .
