name: Cypress Tests

on: [push]

jobs:
  setup:
      runs-on: ubuntu-latest
      container: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Cypress install
          uses: cypress-io/github-action@v5
          with:
            runTests: false

        - name: Cache Cypress
          uses: actions/cache@v3
          with:
            path: ~/.cache/Cypress
            key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

        - name: Cache node modules
          uses: actions/cache@v3
          with:
            path: node_modules
            key: node_modules-${{ hashFiles('package-lock.json') }}
            # loading an older version is fine here, since it will get an npm install
            restore-keys: |
              node_modules-

        - name: Install dependencies
          run: npm ci

  ui-chrome-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
    needs: setup
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
          # no restore-keys here, so we only accept this exact version

      - name: Load cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v5
        with:
          install: false
          start: npm start
          wait-on: http://localhost:4200
          browser: chrome
          record: true
          parallel: true
          group: "UI - Chrome"
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

  ui-firefox-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --user 1001
    needs: setup
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
          # no restore-keys here, so we only accept this exact version

      - name: Load cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: "UI Tests - Firefox"
        uses: cypress-io/github-action@v5
        with:
          install: false
          start: npm start
          wait-on: http://localhost:4200
          browser: firefox
          record: true
          parallel: true
          group: "UI - Firefox"
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

  ui-edge-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
    needs: setup
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
          # no restore-keys here, so we only accept this exact version

      - name: Load cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: "UI Tests - Edge"
        uses: cypress-io/github-action@v5
        with:
          install: false
          start: npm start
          wait-on: http://localhost:4200
          browser: edge
          record: true
          parallel: true
          group: "UI - Edge"
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
